### ISSUE TITLE
Completion computations

### ISSUE THREAD

**Issue by 0rqheus** [Sedatif/EuroDiffusion#3]
You should check if it's completed before for loop.
https://github.com/Sedatif/EuroDiffusion/blob/f3f992e6ac53fbe7da1c105bf4b3871862f13b6d/main.py#L29-L33

And you should use the same "completed" property here.
https://github.com/Sedatif/EuroDiffusion/blob/f3f992e6ac53fbe7da1c105bf4b3871862f13b6d/main.py#L80-L84

**Comment by Sedatif** [comment]
We dont need to check before loop. If one city be not completed we must return False.  That`s why we check in loop.
